@startuml Baseline_4
left to right direction
skinparam packageStyle rectangle
skinparam nodesep 10

package "Oplever fase"{
    rectangle "Componenten"as 1
    rectangle "Project plan" as 1_plan
    rectangle "Analyse document" as 1_analyse
    rectangle "Software Architectuur document" as 1_sad
    1 -.> 1_plan
    1 -.> 1_analyse
    1 -.> 1_sad
    
    rectangle "<I>Verslag" as report
    rectangle "<I>Prototype \nGeneric db" as prototype0
    rectangle "<I>Prototype \ndatamodel\nklonen" as prototype1
    rectangle "<I>Prototype \npseudonimiseren" as prototype2
    1 -.> report
    1 -.> prototype0
    1 -.> prototype1
    1 -.> prototype2
    
    rectangle "Front-end" as frontend
    rectangle "Back-end" as backend
    rectangle "Bouwstraat" as pipeline
    1 -.> frontend
    1 -.> backend
    1 -.> pipeline
    
    rectangle "Oplever document" as transfer
    1 --> transfer
}
@enduml